/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import javax.swing.JOptionPane;

import br.ulbra.entity.TrabalhoPerfume;

/**
 *
 * @author aluno.saolucas
 */
public class FrLista extends javax.swing.JFrame {

    /**
     * Creates new form FrLista
     */
    public FrLista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCodigo = new javax.swing.JLabel();
        TXTCodigo = new javax.swing.JTextField();
        BTNAlterar = new javax.swing.JButton();
        lbModificar = new javax.swing.JLabel();
        TXTPerfume2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbPerfume2 = new javax.swing.JLabel();
        BTNquant = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        BNTOrdenar = new javax.swing.JButton();
        BNTListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTlistaPefume = new javax.swing.JTextArea();
        BTNsalvar = new javax.swing.JButton();
        TXTNomeProduto = new javax.swing.JTextField();
        lbNomeProduto = new javax.swing.JLabel();
        lbProduto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TXTCodigoEx = new javax.swing.JTextField();
        BTNExcluir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lbPesquisar = new javax.swing.JLabel();
        TXTProcurar = new javax.swing.JTextField();
        BTNProcurar = new javax.swing.JButton();
        lbPesquisarProduto = new javax.swing.JLabel();
        lbListaPerfume = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbCodigo.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        lbCodigo.setText("Código");

        TXTCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCodigoActionPerformed(evt);
            }
        });

        BTNAlterar.setText("ALTERAR");
        BTNAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAlterarActionPerformed(evt);
            }
        });

        lbModificar.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lbModificar.setText("MODIFICAR");

        TXTPerfume2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPerfume2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setBackground(new java.awt.Color(0, 51, 204));
        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\Downloads\\bottle_15675418.png")); // NOI18N
        jLabel1.setText("SANDES PERFUMARIA  ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        lbPerfume2.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        lbPerfume2.setText("Perfume");

        BTNquant.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTNquant.setText("QUANTIDADE");
        BTNquant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNquantActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLimpar.setText("LIMPAR ");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        BNTOrdenar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BNTOrdenar.setText("ORDENAR");
        BNTOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNTOrdenarActionPerformed(evt);
            }
        });

        BNTListar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BNTListar.setText("LISTAR");
        BNTListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNTListarActionPerformed(evt);
            }
        });

        TXTlistaPefume.setColumns(20);
        TXTlistaPefume.setRows(5);
        TXTlistaPefume.setAutoscrolls(false);
        TXTlistaPefume.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 255)));
        jScrollPane1.setViewportView(TXTlistaPefume);

        BTNsalvar.setText("SALVAR");
        BTNsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNsalvarActionPerformed(evt);
            }
        });

        TXTNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNomeProdutoActionPerformed(evt);
            }
        });

        lbNomeProduto.setBackground(new java.awt.Color(0, 0, 0));
        lbNomeProduto.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        lbNomeProduto.setText("Nome do Produto");

        lbProduto.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lbProduto.setText("PRODUTO");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Código");

        TXTCodigoEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCodigoExActionPerformed(evt);
            }
        });

        BTNExcluir.setText("EXCLUIR");
        BTNExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNExcluirActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jLabel8.setText("EXCLUIR PERFUME");

        lbPesquisar.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        lbPesquisar.setText("Pesquisar");

        TXTProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTProcurarActionPerformed(evt);
            }
        });

        BTNProcurar.setText("PROCURAR");
        BTNProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNProcurarActionPerformed(evt);
            }
        });

        lbPesquisarProduto.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lbPesquisarProduto.setText("PESQUISAR PRODUTO");

        lbListaPerfume.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lbListaPerfume.setText("LISTA DE PERFUME");

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPerfume2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTPerfume2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbProduto)
                    .addComponent(lbNomeProduto)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TXTNomeProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbListaPerfume, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TXTProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BTNProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTCodigoEx, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BTNExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(247, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpar)
                            .addComponent(BNTOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BNTListar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNquant, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProduto)
                    .addComponent(lbPesquisarProduto)
                    .addComponent(lbListaPerfume, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbNomeProduto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbPesquisar)
                                    .addComponent(TXTProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTNProcurar))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TXTNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BTNsalvar)
                                .addGap(130, 130, 130)
                                .addComponent(lbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel8)
                                .addGap(1, 1, 1)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTCodigoEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTNExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPerfume2)
                            .addComponent(TXTPerfume2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCodigo)
                            .addComponent(TXTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNAlterar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BNTListar)
                            .addComponent(BNTOrdenar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpar)
                            .addComponent(BTNquant))))
                .addGap(0, 2420, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNomeProdutoActionPerformed
    TrabalhoPerfume bancoDeDados = new TrabalhoPerfume();

    private void BTNsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNsalvarActionPerformed
        bancoDeDados.salvar(TXTNomeProduto.getText());
        TXTlistaPefume.setText(bancoDeDados.listar());
    }//GEN-LAST:event_BTNsalvarActionPerformed

    private void TXTCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCodigoActionPerformed

    private void BTNAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAlterarActionPerformed
        bancoDeDados.alterar(Integer.parseInt(TXTCodigo.getText()), TXTPerfume2.getText());
        TXTlistaPefume.setText(bancoDeDados.listar());
    }//GEN-LAST:event_BTNAlterarActionPerformed

    private void BTNExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNExcluirActionPerformed
        bancoDeDados.excluir(Integer.parseInt(TXTCodigoEx.getText()));
        TXTlistaPefume.setText(bancoDeDados.listar());
    }//GEN-LAST:event_BTNExcluirActionPerformed

    private void TXTPerfume2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPerfume2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPerfume2ActionPerformed

    private void TXTCodigoExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCodigoExActionPerformed
        bancoDeDados.excluir(Integer.parseInt(TXTCodigo.getText()));
        TXTlistaPefume.setText(bancoDeDados.listar());
    }//GEN-LAST:event_TXTCodigoExActionPerformed

    private void BTNquantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNquantActionPerformed
        int quantidade = bancoDeDados.quantidade();
        JOptionPane.showMessageDialog(null, "Total de produtos: " + quantidade);

    }//GEN-LAST:event_BTNquantActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        bancoDeDados.limparLista();
        TXTlistaPefume.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void BNTOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNTOrdenarActionPerformed
// Ordena a lista de produtos alfabeticamente
    bancoDeDados.ordenarAlfabeticamente();

    // Cria uma string com os produtos ordenados
    StringBuilder listaFinal = new StringBuilder("Lista de produtos ordenada:\n");
    for (String produto : bancoDeDados.Alfabetica) {
        listaFinal.append(produto).append("\n");
    }

    // Atualiza o campo de texto com a lista ordenada
    TXTlistaPefume.setText(listaFinal.toString());
    }//GEN-LAST:event_BNTOrdenarActionPerformed

    private void BNTListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNTListarActionPerformed
        bancoDeDados.resetarLista();

    // Cria uma string com os produtos na ordem original
    StringBuilder listaFinal = new StringBuilder("Lista de produtos na ordem original:\n");
    for (String produto : bancoDeDados.Original) {
        listaFinal.append(produto).append("\n");
    }

    // Atualiza o campo de texto com a lista na ordem original
    TXTlistaPefume.setText(listaFinal.toString());;    }//GEN-LAST:event_BNTListarActionPerformed

    private void TXTProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTProcurarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTProcurarActionPerformed

    private void BTNProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNProcurarActionPerformed
        String produtoBuscado = TXTProcurar.getText().trim();  // Pega o produto digitado no campo de texto

    // Verifica se o campo não está vazio
    if (!produtoBuscado.isEmpty()) {
        boolean encontrado = false; // Flag para saber se encontrou o produto

        // Itera sobre a lista de produtos
        for (String produto : bancoDeDados.Alfabetica) {
            // Verifica se o produto digitado está na lista (ignora maiúsculas/minúsculas)
            if (produto.equalsIgnoreCase(produtoBuscado)) {
                JOptionPane.showMessageDialog(null, "Produto encontrado: " + produto);
                encontrado = true;
                break;  // Interrompe o loop se o produto for encontrado
            }
        }

        // Caso o produto não tenha sido encontrado
        if (!encontrado) {
            JOptionPane.showMessageDialog(null, "Produto não encontrado.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Digite um produto para procurar.");
    }//GEN-LAST:event_BTNProcurarActionPerformed
    }
        
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrLista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BNTListar;
    private javax.swing.JButton BNTOrdenar;
    private javax.swing.JButton BTNAlterar;
    private javax.swing.JButton BTNExcluir;
    private javax.swing.JButton BTNProcurar;
    private javax.swing.JButton BTNquant;
    private javax.swing.JButton BTNsalvar;
    private javax.swing.JTextField TXTCodigo;
    private javax.swing.JTextField TXTCodigoEx;
    private javax.swing.JTextField TXTNomeProduto;
    private javax.swing.JTextField TXTPerfume2;
    private javax.swing.JTextField TXTProcurar;
    private javax.swing.JTextArea TXTlistaPefume;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbListaPerfume;
    private javax.swing.JLabel lbModificar;
    private javax.swing.JLabel lbNomeProduto;
    private javax.swing.JLabel lbPerfume2;
    private javax.swing.JLabel lbPesquisar;
    private javax.swing.JLabel lbPesquisarProduto;
    private javax.swing.JLabel lbProduto;
    // End of variables declaration//GEN-END:variables
}
